### ISSUE TITLE
Request to support metadata import for Drupal 8

### ISSUE THREAD

**Issue by yanyuqiang** [apigee/apigee-smartdocs-maven-plugin#15]
Drupal 7 version supports advance implementation for model metadata import (https://github.com/apigee/apigee-smartdocs-maven-plugin/tree/master/samples/Drupal7#advanced-implementation-model-metadata-import). We really need this feature in Drupal 8. More specifically

1. We need the ability to publish data stored within the info object to fields we created in API Doc
2. Since we have different APIs with the same API name, so we need the ability to config the API Doc name on the devportal (https://github.com/apigee/apigee-smartdocs-maven-plugin/tree/master/samples/Drupal7#configuring-the-model-name-on-the-developer-portal-optional).

**Comment by ssvaidyanathan** [comment]
Available in v2.1.0
Refer to the [samples](https://github.com/apigee/apigee-smartdocs-maven-plugin/tree/master/samples/Drupal8)
