### ISSUE TITLE
Change in Drupal API Catalog endpoint

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-smartdocs-maven-plugin#16]
We are planning a 2.0 release of [Drupal API Catalog module](apigee-api-catalog-drupal) which [changes the custom Drupal entity "APIDoc" into a Node type instead](https://github.com/apigee/apigee-api-catalog-drupal/issues/71). 

This will unfortunately change the endpoint that needs to be called from the Maven plugin project. The [Apigee API Catalog Drupal module](https://github.com/apigee/apigee-api-catalog-drupal) will now have two major versions:

* `1.x`: Same endpoint as before for making CRUD calls for API Doc entity.
* `2.x`: New endpoint for making CRUD calls for API Doc entity.

This issue is to have a way to make calls to the correct endpoint depending on which version you are using.

**Comment by arlina-espinoza** [comment]
Hi team,

The change for the 2.x version is that the endpoint changes from `/jsonapi/apidoc/apidoc` to `/jsonapi/node/apidoc`. The field names had to change too:
- `name` to `title`
- `description` to `body`
- `spec_file_source` to `field_apidoc_spec_file_source`
- `file_link` to `field_apidoc_file_link`

**Comment by arlina-espinoza** [comment]
Here's a link to a postman collection for version 2.x of the module: 
https://documenter.getpostman.com/view/550470/S1a1aoeF?version=2c9ff08d-6e80-4fb9-b303-553f40e0e790

**Comment by ssvaidyanathan** [comment]
Available in v2.1.0
