### ISSUE TITLE
Does it work with localhost drupal portal?

### ISSUE THREAD

**Issue by simantstha** [apigee/apigee-smartdocs-maven-plugin#46]
I have apigee kickstarter setup and i wanted to use your plugin. So i wanted to ask if it is possible to do that.

**Comment by ssvaidyanathan** [comment]
yes you can - just update the portal.url in the Maven config (inside your pom.xml) to point to it

**Comment by simantstha** [comment]
I am very new to this. Is there any simple step by step implementation of this. As per my knowledge i download the zip folder and keep it inside "contrib" folder? all the modules are there. After i edit the pom.xml what should i do to trigger the API documentation. Can you explain in simple steps thank you.

**Comment by ssvaidyanathan** [comment]
Hi @simantstha 
Check out the samples folder in the repo. You can just clone the repo to your machine
Go to the sample directory, update the values in that pom.xml inside samples and then call the mvn command with all the arguments. There is a README provided in the sample directory too that can help you with all steps

**Comment by simantstha** [comment]
Thank you for a quick response. Will do that.

**Comment by simantstha** [comment]
<img width="1440" alt="Screen Shot 2022-07-01 at 10 42 30 AM" src="https://user-images.githubusercontent.com/30699044/176927081-37d2b95c-3725-4c95-88da-056f392bdc92.png">
<img width="718" alt="Screen Shot 2022-07-01 at 10 43 46 AM" src="https://user-images.githubusercontent.com/30699044/176927281-ceb82587-f5ec-4677-b0bb-b0dd6e080d2e.png">

**Comment by simantstha** [comment]
Am i putting the values correctly? Also i get that error. Is it necessary for the cloned folder be inside htdocs where drupal site is?

**Comment by simantstha** [comment]
<img width="829" alt="Screen Shot 2022-07-01 at 10 47 37 AM" src="https://user-images.githubusercontent.com/30699044/176927859-dcc0f77a-10a0-47df-a73d-81fa8a4a9568.png">

**Comment by ssvaidyanathan** [comment]
You entries are wrong. You give the values within the tags
For example
```xml
<portal.url>http://abc.com</portal.url>
```

**Comment by simantstha** [comment]
Still getting the same error 
![image](https://user-images.githubusercontent.com/30699044/176930482-17d0c000-5388-4638-86a9-ac0d7f3cf87c.png)

**Comment by ssvaidyanathan** [comment]
You dont have Taxonomy and other setup in your portal.. So you can comment or remove the 
```xml
<apigee.smartdocs.config.file>./apicatalog-config.json</apigee.smartdocs.config.file> <!-- Config for fields --
```
from your pom

**Comment by ssvaidyanathan** [comment]
In your mvn command - change the option from "create" to "update" 
"update" will do create and update. it creates if its not there else updates. So its safer to use "update"

**Comment by simantstha** [comment]
thank you so much for this. It worked.  One last question how can i get the specs from my apigee?

**Comment by ssvaidyanathan** [comment]
Glad it worked!
There are no APIs for that. The recommended approach is you build the spec outside of Apigee using Swagger editor or other tools, commit that to your source code repo and then push it to Drupal portal as part of your pipeline (via Jenkins or whatever tool you use)

**Comment by simantstha** [comment]
Not an issue but i wanted to know if there is such plugin for publishing api proxy in Apigee or not.?

**Comment by ssvaidyanathan** [comment]
I guess you are referring to the deployment of Apigee proxy. If yes, then there is a separate maven tool for that. I guess you already found it and opened an issue.

I am marking this issue here as closed.

**Comment by simantstha** [comment]
I had to uninstall as jsonAPI extras had been working. Now its working fine but getting this error
![image](https://user-images.githubusercontent.com/30699044/182486459-e007b30b-f809-46be-a82b-28601ab91595.png)

**Comment by ssvaidyanathan** [comment]
Its a permission issue. Try checking that and the Drupal logs. This is not a plugin issue. Please debug on your end

**Comment by ssvaidyanathan** [comment]
Also appreciate if you can post as new issue instead of commenting on a closed issue

**Comment by simantstha** [comment]
Sure will do. Appreciate the quick response.
