### ISSUE TITLE
Is there anyway to undo?

### ISSUE THREAD

**Issue by simantstha** [apigee/apigee-smartdocs-maven-plugin#48]
I successfully added the documentation. But i was curious about how can i remove the new update or go back to previous documentation if  the deployment goes south.  Is there any specific commands for that. I know we can do it from the UI of portal but is there any cmd commands which we can do directly from pipeline.

**Comment by ssvaidyanathan** [comment]
@simantstha - you can use the `delete` option
If you want to rollback, then you need to update your source code and then the pipeline will make sure to update that version. In other words, the  source of truth is your repo

**Comment by simantstha** [comment]
Thank you for your response. I used the sync option and It automatically fetched one of the specification from the apigee edge not all. How is it possible?

**Comment by simantstha** [comment]
But delete will remove the api documentation all together but what i mean was there are revisions on drupal development portal. So, instead of deleting is there any other way we can just revert back or tell the portal to revert back to previous version.
