### ISSUE TITLE
Failed to publish SmartDoc when double quote used in description field

### ISSUE THREAD

**Issue by pdu895** [apigee/apigee-smartdocs-maven-plugin#7]
We have Swagger API (2.0) yaml file which contains double quote in description field, although the file is valid and can be uploaded using Developer Portal UI, but it cannot be published using apigee-smartdocs-maven-plugin (1.0.3 and 1.0.4). Can we get this fixed? Thanks.

**Comment by pdu895** [comment]
Here is the portion which causing issue:
swagger: '2.0'
info:
    description: 'This is the service contains generic cross-product information to be found on a "dashboard" or "summary" of various products belonging to a customer.'
...

**Comment by ssvaidyanathan** [comment]
Fixed in v1.0.5
